# Generated by Django 4.2.6 on 2023-11-18 23:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_microfono_tripode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaras',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
