# Generated by Django 4.2.6 on 2023-12-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_camaras_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
