# Generated by Django 4.2.6 on 2023-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_camaras_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaras',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
